
#include <teams.hpp>

Tournament get_current_tournament() {

	// AUTO GENERATED BY TS (JS)

	PointsObject points = PointsObject{};

	points.insert_or_assign(1, 650);
	points.insert_or_assign(2, 550);
	points.insert_or_assign(3, 450);
	points.insert_or_assign(4, 400);
	points.insert_or_assign(5, 350);
	points.insert_or_assign(6, 300);
	points.insert_or_assign(7, 250);
	points.insert_or_assign(8, 220);
	points.insert_or_assign(9, 200);
	points.insert_or_assign(10, 180);
	points.insert_or_assign(11, 150);
	points.insert_or_assign(12, 120);
	points.insert_or_assign(13, 100);
	points.insert_or_assign(14, 70);
	points.insert_or_assign(15, 50);
	points.insert_or_assign(16, 20);

	std::string name = "PGS2 Qualifier";

	Tournament tournament = { name, points };

	return tournament;

	// AUTO GENERATED BY TS (JS)
}
template <std::size_t AMOUNT> std::array<Team<4>, AMOUNT> get_current_teams() {
	// AUTO GENERATED BY TS (JS)
	std::array<Team<4>, AMOUNT> teams{};

	return teams;
	// AUTO GENERATED BY TS (JS)
}
